### ISSUE TITLE
ASAN crash in  #0 0x7efd09910253 in LZ4_decompress_generic ../subprojects/lz4-1.9.3/lib/lz4.c:1948

### ISSUE THREAD

**Issue by XVilka** [lz4/lz4#1023]
**Describe the bug**

During the fuzzing of the Rizin we found the following bug in the LZ4-1.9.3 code.
```
[i] ℤ rz-bin -g 8492d42551499438f5231a8786f1473c                                                                                                                                                                                  13:25:04 
=================================================================
==973415==ERROR: AddressSanitizer: unknown-crash on address 0x6070000594c3 at pc 0x7efd09910254 bp 0x7ffc6878b780 sp 0x7ffc6878b778
WRITE of size 16 at 0x6070000594c3 thread T0
    #0 0x7efd09910253 in LZ4_decompress_generic ../subprojects/lz4-1.9.3/lib/lz4.c:1948
    #1 0x7efd09910253 in LZ4_decompress_safe ../subprojects/lz4-1.9.3/lib/lz4.c:2173
    #2 0x7efd09528f1b in decompress ../librz/bin/p/bin_nso.c:120
    #3 0x7efd09528f1b in decompress ../librz/bin/p/bin_nso.c:108
    #4 0x7efd095295dd in load_buffer ../librz/bin/p/bin_nso.c:145
    #5 0x7efd09478d38 in rz_bin_object_new ../librz/bin/bobj.c:271
    #6 0x7efd09466257 in rz_bin_file_new_from_buffer ../librz/bin/bfile.c:554
    #7 0x7efd0941d34b in rz_bin_open_buf ../librz/bin/bin.c:292
    #8 0x7efd0941ebd7 in rz_bin_open_io ../librz/bin/bin.c:350
    #9 0x7efd129609e2 in rz_main_rz_bin ../librz/main/rz-bin.c:1055
    #10 0x7efd12745b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
    #11 0x4010ad in _start (/home/akochkov/.local/bin/rz-bin+0x4010ad)

0x6070000594d1 is located 0 bytes to the right of 65-byte region [0x607000059490,0x6070000594d1)
allocated by thread T0 here:
    #0 0x7efd12ae7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x7efd09529553 in load_buffer ../librz/bin/p/bin_nso.c:138
    #2 0x7efd09478d38 in rz_bin_object_new ../librz/bin/bobj.c:271
    #3 0x7efd09466257 in rz_bin_file_new_from_buffer ../librz/bin/bfile.c:554
    #4 0x7efd0941d34b in rz_bin_open_buf ../librz/bin/bin.c:292
    #5 0x7efd0941ebd7 in rz_bin_open_io ../librz/bin/bin.c:350
    #6 0x7efd129609e2 in rz_main_rz_bin ../librz/main/rz-bin.c:1055
    #7 0x7efd12745b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

SUMMARY: AddressSanitizer: unknown-crash ../subprojects/lz4-1.9.3/lib/lz4.c:1948 in LZ4_decompress_generic
Shadow bytes around the buggy address:
  0x0c0e80003240: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x0c0e80003250: fd fd fd fd fd fa fa fa fa fa fd fd fd fd fd fd
  0x0c0e80003260: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0e80003270: fd fd fa fa fa fa fd fd fd fd fd fd fd fd fd fd
  0x0c0e80003280: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fa fa
=>0x0c0e80003290: fa fa 00 00 00 00 00 00[00]00 01 fa fa fa fa fa
  0x0c0e800032a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e800032b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e800032c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e800032d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e800032e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==973415==ABORTING
```

**Expected behavior**

No crash

**To Reproduce**

Feed the `lz4_buf_0x00000009.bin` file to the `LZ4_decompress_safe((const char *)tmp, (char *)dst_buf, source_size, decompressed_size);`.
See the following code on how exactly we use it.

```c
static bool decompress(RzBuffer *source_buf, ut64 source_offset, ut64 source_size, ut8 *dst_buf, ut64 decompressed_size) {
	if (!source_size || decompressed_size > (ut64)SIZE_MAX || source_size > (ut64)INT_MAX || decompressed_size > (ut64)INT_MAX) {
		return false;
	}
	ut8 *tmp = RZ_NEWS0(ut8, source_size);
	if (!tmp) {
		return false;
	}
	if (rz_buf_read_at(source_buf, source_offset, tmp, source_size) != source_size) {
		free(tmp);
		return false;
	}
	int r = LZ4_decompress_safe((const char *)tmp, (char *)dst_buf, source_size, decompressed_size);
	free(tmp);
	return r == decompressed_size;
}
```
```
[i] ℤ rizin -nn lz4_buf_0x00000009.bin                                                                                                                                                                                            13:52:45 
[0x00000000]> px
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  ff0d 1aef 3000 6709 0000 0000 da00 005d  ....0.g........]
0x00000010  0000 0000 046e 0046 0000 0000 0000 0000  .....n.F........
0x00000020  0000 0000 0000 0000 0000 0000 0000 00e4  ................
0x00000030  ffff ff00 0000 0030 3030 3030 30ff ffff  .......000000...
```

**System (please complete the following information):**
 - OS: Fedora Linux
 - Version 34
 - Compiler: gcc 11
 - Build System Meson/Ninja

**Additional context**

Attached the original file that caused the Rizin crash when called `rz-bin -g 8492d42551499438f5231a8786f1473c` and the exact data chunk that is fed to the LZ4 decompress code.

[lz4_buf_0x00000009.bin.zip](https://github.com/lz4/lz4/files/7019405/lz4_buf_0x00000009.bin.zip)
[8492d42551499438f5231a8786f1473c.zip](https://github.com/lz4/lz4/files/7019408/8492d42551499438f5231a8786f1473c.zip)

**Comment by XVilka** [comment]
Sorry for the noise, our fault: https://github.com/rizinorg/rizin/pull/1480#issuecomment-902499848
